# Generated by Django 2.0.1 on 2018-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='images/a.png', max_length=100, verbose_name='图片地址')),
                ('advantage', models.CharField(max_length=100, verbose_name='服务优势')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MEDIA_ROOT', verbose_name='图片Url')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='易讯通', max_length=10, verbose_name='公司名')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
                ('zip_code', models.IntegerField(verbose_name='邮政编码')),
                ('contact_address', models.CharField(max_length=50, verbose_name='公司地址')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='images/a.png', max_length=100, verbose_name='图片地址')),
                ('people', models.CharField(max_length=100, verbose_name='服务人群')),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_image', models.CharField(default='images/icon-01.png', max_length=20, verbose_name='图片Url')),
                ('provide_title', models.CharField(max_length=20, verbose_name='服务名称')),
                ('provide_text', models.CharField(max_length=100, verbose_name='服务内容')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='images/img-20.png', max_length=20, verbose_name='图片Url')),
                ('title', models.CharField(max_length=20, verbose_name='服务名称')),
                ('text', models.CharField(max_length=100, verbose_name='服务内容')),
            ],
        ),
    ]
