# Generated by Django 2.0.1 on 2018-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='images/jigou-img-01.png', max_length=30, verbose_name='图片Url'),
        ),
    ]
