# Generated by Django 2.0.1 on 2018-05-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20180508_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='关键词:', max_length=200, verbose_name='关键词'),
        ),
    ]
