# Generated by Django 2.0.5 on 2018-05-10 03:48

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
