# Generated by Django 2.0.5 on 2018-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20180510_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
    ]
