# Generated by Django 2.0.5 on 2018-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_article_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=120, verbose_name='摘要'),
        ),
    ]
