# Generated by Django 2.0.5 on 2018-05-10 07:06

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20180510_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
