# Generated by Django 2.0.5 on 2018-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20180510_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='desc',
            field=models.TextField(default='', max_length=120, verbose_name='摘要'),
        ),
    ]
