# Generated by Django 2.0.5 on 2018-05-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_industry_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=120, verbose_name='摘要'),
        ),
    ]
