# Generated by Django 2.0.5 on 2018-05-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20180511_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-pub_date']},
        ),
    ]
